### ISSUE TITLE
If MAIL FROM is local then you must authenticate

### ISSUE THREAD

**Issue by ImranAhmed** [andrewdavey/postal#127]
Hi,

Great library. This has been working for some time in PROD without any issues however I've just started getting this error. Has anyone come across this before?

System.Net.Mail.SmtpException: Mailbox unavailable. The server response was: If MAIL FROM is local then you must authenticate
   at System.Net.Mail.MailCommand.CheckResponse(SmtpStatusCode statusCode, String response)
   at System.Net.Mail.MailCommand.Send(SmtpConnection conn, Byte[] command, MailAddress from, Boolean allowUnicode)
   at System.Net.Mail.SmtpTransport.SendMail(MailAddress sender, MailAddressCollection recipients, String deliveryNotify, Boolean allowUnicode, SmtpFailedRecipientException& exception)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Postal.EmailService.Send(Email email)
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)

**Comment by ImranAhmed** [comment]
ok, fixed it, looks like my mail server settings changed. I had to authenticate using username/password and create an smtp client.
