### ISSUE TITLE
System.NotImplementedException under .net 4.5/MVC 4

### ISSUE THREAD

**Issue by dsghi** [andrewdavey/postal#30]
Here's the stack trace

System.NotImplementedException was unhandled by user code
  Message=The method or operation is not implemented.
  Source=System.Web
  StackTrace:
       at System.Web.HttpResponseBase.get_Cookies()
       at System.Web.WebPages.CookieBrowserOverrideStore.GetOverriddenUserAgent(HttpContextBase httpContext)
       at System.Web.WebPages.BrowserHelpers.GetOverriddenUserAgent(HttpContextBase httpContext)
       at System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext, Func`2 createBrowser)
       at System.Web.WebPages.BrowserHelpers.GetOverriddenBrowser(HttpContextBase httpContext)
       at System.Web.WebPages.DisplayModes.<.cctor>b__b(HttpContextBase context)
       at System.Web.WebPages.DefaultDisplayMode.CanHandleContext(HttpContextBase httpContext)
       at System.Web.WebPages.DisplayModes.<>c__DisplayClass2.<GetAvailableDisplayModesForContext>b__1(IDisplayMode mode)
       at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
       at System.Web.Mvc.VirtualPathProviderViewEngine.GetPath(ControllerContext controllerContext, String[] locations, String[] areaLocations, String locationsPropertyName, String name, String controllerName, String cacheKeyPrefix, Boolean useCache, String[]& searchedLocations)
       at System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache)
       at System.Web.Mvc.ViewEngineCollection.<>c__DisplayClassc.<FindView>b__a(IViewEngine e)
       at System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths)
       at System.Web.Mvc.ViewEngineCollection.FindView(ControllerContext controllerContext, String viewName, String masterName)
       at Postal.EmailViewRenderer.CreateView(String viewName, ControllerContext controllerContext)
       at Postal.EmailViewRenderer.Render(Email email, String viewName)
       at Postal.EmailService.CreateMailMessage(Email email)
       at Postal.EmailService.Send(Email email)
       at Postal.Email.Send()
       at XY.Controllers.MailController.Index() in c:\dev\xy\Controllers\MailController.cs:line 55
       at lambda_method(Closure , ControllerBase , Object[] )
       at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
       at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
       at System.Web.Mvc.ControllerActionInvoker.<>c__DisplayClass15.<InvokeActionMethodWithFilters>b__12()
       at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethodFilter(IActionFilter filter, ActionExecutingContext preContext, Func`1 continuation)
  InnerException:

**Comment by djanosik** [comment]
Hi, have you managed to fix this issue?

**Comment by dsghi** [comment]
I didn't work too hard to look into this, but since I also ran into issue #32, so I've switched to ActionMailer.Net

**Comment by dasmod** [comment]
Same here. Shall we wait or switch?

**Comment by irobinson** [comment]
Just switched to ActionMailer.Net - pretty painless!

**Comment by andrewdavey** [comment]
Postal 0.8.0 is now in nuget. It contains a build that targets .NET 4.5
