### ISSUE TITLE
Postal is failing in Unit Tests

### ISSUE THREAD

**Issue by dotnetchris** [andrewdavey/postal#36]
Tests are ran as MSpec + Machine.Fakes

Web App is MVC3, inside is RegistrationOrchestrator which is the class I'm testing. The orchestrator initiates the send email with the view located in Views/Emails/ and this works correctly when ran as a web app.

When this is executed from the unit test:

exception   {"Object reference not set to an instance of an object."}   System.Exception {System.NullReferenceException}
InnerException  null    System.Exception
Source  "System.Web"    string

StackTrace  

   at System.Web.VirtualPath.GetCacheKey()
   at System.Web.Compilation.BuildManager.GetCacheKeyFromVirtualPath(VirtualPath virtualPath, Boolean& keyFromVPP)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultFromCacheInternal(VirtualPath virtualPath, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetObjectFactory(String virtualPath, Boolean throwIfNotFound)
   at System.Web.Mvc.BuildManagerWrapper.System.Web.Mvc.IBuildManager.FileExists(String virtualPath)
   at System.Web.Mvc.BuildManagerViewEngine.FileExists(ControllerContext controllerContext, String virtualPath)
   at System.Web.Mvc.VirtualPathProviderViewEngine.GetPathFromGeneralName(ControllerContext controllerContext, List`1 locations, String name, String controllerName, String areaName, String cacheKey, String[]& searchedLocations)
   at System.Web.Mvc.VirtualPathProviderViewEngine.GetPath(ControllerContext controllerContext, String[] locations, String[] areaLocations, String locationsPropertyName, String name, String controllerName, String cacheKeyPrefix, Boolean useCache, String[]& searchedLocations)
   at System.Web.Mvc.VirtualPathProviderViewEngine.FindView(ControllerContext controllerContext, String viewName, String masterName, Boolean useCache)
   at System.Web.Mvc.ViewEngineCollection.<>c__DisplayClassc.<FindView>b__b(IViewEngine e)
   at System.Web.Mvc.ViewEngineCollection.Find(Func`2 lookup, Boolean trackSearchedPaths)
   at System.Web.Mvc.ViewEngineCollection.Find(Func`2 cacheLocator, Func`2 locator)
   at System.Web.Mvc.ViewEngineCollection.FindView(ControllerContext controllerContext, String viewName, String masterName)
   at Postal.EmailViewRenderer.CreateView(String viewName, ControllerContext controllerContext)
   at Postal.EmailViewRenderer.Render(Email email, String viewName)
   at Postal.EmailService.CreateMailMessage(Email email)
   at Postal.EmailService.Send(Email email)
   at Postal.Email.Send()
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at Orchestrators.RegistrationOrchestrator.TrySendEmail(RegistrationViewModel newRegistration) in C:\Projects..Orchestrators\RegistrationOrchestrator.cs:line 97

**Comment by andrewdavey** [comment]
The view engine infrastructure that Postal uses is very tied to ASP.NET. So running outside of this context is always going to cause problems.

Options available:

1- Switch to using Postal's `FileSystemRazorViewEngine`

``` csharp
var engines = new ViewEngineCollection();
engines.Add(new FileSystemRazorViewEngine(viewsPath));
var service = new EmailService(engines);
service.Send(myEmail);
```

This uses the RazorEngine library, which hasn't always provided support for all of Razor's features, but may be enough for your needs.

2- Don't test the rendering of the email views in a unit test. Instead mock and verify Postal's `IEmailService.Send` method.

``` csharp
var emailService = new Mock<IEmailService>();
dynamic email = null;
emailService.Setup(s=>s.Send(It.IsAny<Email>())).Callback<Email>(e => email = e);
// pass the emailService to your RegistrationOrchestrator
// call TrySendEmail...
// then assert things about he email object.
Asset.Equal("example", email.Subject);
```

**Comment by dotnetchris** [comment]
Thanks for the update on this Andrew, going with the verified call to Send should be good enough from my specification level, i have an integration test that i can use for rendering the email. I was just wondering if there was a simple fix here.

I might try the filesystem engine but I'm extremely hesitant to adding view engines, i'm using a custom view engine and i always have fear of apocalypse from adding another view engine and that some of my expectations in my custom view engine causes chaos with it.

**Comment by dotnetchris** [comment]
Switched from using new Email().Send() to taking an explicit dependency to IEmailService and the peasants rejoice.

**Comment by Abrahamlincoln97** [comment]
Looks like Postal's trying to render a view using MVC's view engine, which doesn't initialize in unit test context. Mocking the view engine or [game vault 999 apk](https://gamevault999apk.us/) abstracting email rendering logic usually helps avoid the NullReferenceException.
