### ISSUE TITLE
Could not load file or assembly 'RazorEngine, Version=3.3.0.0

### ISSUE THREAD

**Issue by Misterhex** [andrewdavey/postal#67]
Hi, 
I am getting a "Could not load file or assembly 'RazorEngine, Version=3.3.0.0, Culture=neutral, PublicKeyToken=9ee697374c7e744a' or one of its dependencies. The system cannot find the file specified." 
( based on the example [http://aboutcode.net/postal/outside-aspnet.html](http://aboutcode.net/postal/outside-aspnet.html) )

environment: 
VS 2013, using postal in class library.  postal 0.9.1, .net 4.5.1

stack trace:
   at Postal.FileSystemRazorView.Render(ViewContext viewContext, TextWriter writer)
   at Postal.EmailViewRenderer.RenderView(IView view, ViewDataDictionary viewData, ControllerContext controllerContext)
   at Postal.EmailViewRenderer.Render(Email email, String viewName)
   at Postal.EmailService.CreateMailMessage(Email email)
   at Postal.EmailService.Send(Email email)
   at CallSite.Target(Closure , CallSite , EmailService , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at Vortex.Postman.MemberRegistrationObserver.OnReceivingEvent(MemberRegistration value) in c:\Users\KERITOS-005\Documents\GitHub\Vortex\Vortex\Vortex.Postman\Controller.cs:line 66
   at Vortex.Postman.PostalEventObserver`1.OnNextCore(TEvent value) in c:\Users\KERITOS-005\Documents\GitHub\Vortex\Vortex\Vortex.Postman\Controller.cs:line 99

**Comment by Misterhex** [comment]
resolved by manually adding nuget package [RazorEngine](https://www.nuget.org/packages/RazorEngine/)
