### ISSUE TITLE
EmailService ViewModel

### ISSUE THREAD

**Issue by lucho07** [andrewdavey/postal#72]
Hello, could you please add an example about how to use EmailService with a viewModel instead using ViewBag?

**Comment by andrewdavey** [comment]
Have you seen http://aboutcode.net/postal/strongly-typed-emails.html ?

**Comment by lucho07** [comment]
Yes, but in my project we use Postal 0.7.3. I need to use the IEmailService interface for sending (passing) the model to the view.

**Comment by andrewdavey** [comment]
Does this work... ?

```
public class ExampleEmail : Email
{
    public string To { get; set; }
    public string Message { get; set; }
}
```

```
var emailService = new EmailService();
var email = new ExampleEmail { To = "test@example.com", Message = "hello" };
emailService.Send(email);
```

**Comment by lucho07** [comment]
No, it doesn't show that error object reference not set to an instance of an object.
That's happening only when the view has a model, if not, it send the mail properly

**Comment by andrewdavey** [comment]
Sorry, this isn't enough information for me to help to diagnose the problem. It would be useful to have a full stack trace of the exception, and also to see the controller code and the email view cshtml file.

**Comment by lucho07** [comment]
Andrew, I'm attaching the codes. However, I'm not sure if you'll understand it.

```
    My Class *************************************************

    private readonly IEmailService _emailService;
    private readonly string _sSource = ConfigurationManager.AppSettings["NombreApp"];

    Constructor *********************************************
    public EnvioEmailsManager( IEmailService emailService )
    {
        _emailService = emailService;
    }

    Method send email ********************************************************
    public void EnvioMailBloqueoNotificacion(EmailBloqueoNotificacion EmailBloqueoNotificacion)
    {
        var notificacion = ConfigurarNotificacion( "TemplateEmailBloqueoNotificacion",     EmailBloqueoNotificacion );

        _emailService.Send( notificacion );
    }

    Method that load model ***************************************************
    private NotificacionBloqueoNotif ConfigurarNotificacion( string nombreTemplate, EmailBloqueoNotificacion emailBloqueoNotificacion )
    {
        return new NotificacionBloqueoNotif( nombreTemplate ) { EmailBloqueoNotificacion = emailBloqueoNotificacion };
    }

     Model ***************************************

     public class NotificacionBloqueoNotif : Email
    {
    #region Propiedades

   public EmailBloqueoNotificacion EmailBloqueoNotificacion { get; set; }

    #endregion Propiedades

    #region Constructores

    public NotificacionBloqueoNotif(string viewName)
        : base(viewName)
    {
        ViewName = viewName;
    }

    #endregion Constructores
    }

     My View ***********************************************************
```

```
To: @Model.EmailBloqueoNotificacion.EmailNotificacion
Subject: @Model.EmailBloqueoNotificacion.Subject
From: @Model.EmailBloqueoNotificacion.From
Content-Type: text/html

<!DOCTYPE html>

<html>
<head>
</head>
    <body>
        <div id="mail">
        <b>At. @Model.EmailBloqueoNotificacion.Name:</b>

    </body>
</html>
```

**Comment by andrewdavey** [comment]
Is your view missing this line at the start of the file?

```
@model YourAppNamespace.NotificacionBloqueoNotif
```

**Comment by lucho07** [comment]
No, I forgot to add it in the message.

**Comment by andrewdavey** [comment]
OK. I will need to see a full stack trace of the exception you are getting please.

**Comment by lucho07** [comment]
I attached the trace:

   at RazorEngine.Templating.TemplateBase.Write(TemplateWriter helper)
   at CallSite.Target(Closure , CallSite , befabaead , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   at CompiledRazorTemplates.Dynamic.befabaead.Execute()
   at RazorEngine.Templating.TemplateBase.RazorEngine.Templating.ITemplate.Run(ExecuteContext context)
   at RazorEngine.Templating.TemplateService.Run(ITemplate template)
   at RazorEngine.Templating.TemplateService.Parse(String razorTemplate, Object model, String name)
   at RazorEngine.Razor.Parse(String razorTemplate, Object model, String name)
   at Postal.FileSystemRazorView.Render(ViewContext viewContext, TextWriter writer)
   at Postal.EmailViewRenderer.RenderView(IView view, ViewDataDictionary viewData, ControllerContext controllerContext)
   at Postal.EmailViewRenderer.Render(Email email, String viewName)
   at Postal.EmailService.CreateMailMessage(Email email)
   at Postal.EmailService.Send(Email email)
   at ControlCredito.Application.Business.EnvioEmailsManager.EnvioMailNotificado(EmailBloqueoNotificacion EmailBloqueoNotificacion) in C:\Codigo Fuente\ControlCredito\ControlCredito.Application\Business\EnvioEmailsManager.cs:line 54
   at ControlCredito.Application.Entities.EnvioMailScc.SendMailHtmlPv(DatosPV datosPV, SCCPVv2Config ConfigActTop) in C:\Codigo Fuente\ControlCredito\ControlCredito.Application\Entities\EnvioMailScc.cs:line 65
   at ControlCredito.Application.ProcesoControlCreditoPv.EnviarEmailPv(DatosPV datosPv, SCCPVv2Config configActTop) in C:\Codigo Fuente\ControlCredito\ControlCredito.Application\ProcesoControlCreditoPv.cs:line 149
   at ControlCredito.Application.ProcesoControlCreditoPv.ProcesarPv(Int32 idPv) in C:\Codigo Fuente\ControlCredito\ControlCredito.Application\ProcesoControlCreditoPv.cs:line 78

**Comment by andrewdavey** [comment]
Sorry, I still can't work out what is broken here. I see that you are using RazorEngine via Postal's FileSystemRazorViewEngine. Have you tried not using this and just letting Postal use the default MVC view engine instead?

**Comment by lucho07** [comment]
Hi, I have already solved it. The problem was that the object had NULL value.
